.SECONDEXPANSION:

interfaces.o: 
interfaces.o = interfaces.o 
_modobj_fycollections_interfaces = interfaces.o

module.o: $$(_modobj_fycollections_interfaces) $$(_modobj_fycollections_ptrlist)
module.o = module.o $($(_modobj_fycollections_interfaces)) $($(_modobj_fycollections_ptrlist))
_modobj_fycollections = module.o

ptrlist.o: $$(_modobj_fycollections_common) $$(_modobj_fycollections_interfaces)
ptrlist.o = ptrlist.o $($(_modobj_fycollections_common)) $($(_modobj_fycollections_interfaces))
_modobj_fycollections_ptrlist = ptrlist.o

common.o: 
common.o = common.o 
_modobj_fycollections_common = common.o

